spring.application.name=caching

spring.datasource.url=jdbc:postgresql://localhost:5432/dev
spring.datasource.username=postgres
spring.datasource.password=password

spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

#redis configuration
#spring.data.redis.host=localhost
#spring.data.redis.port=6379

spring.data.redis.host=redis-15669.crce300.ap-south-1-2.ec2.cloud.redislabs.com
spring.data.redis.port=15669
spring.data.redis.password=WcgcarORhjCQteIOdratbLEVwzrpOZfb
